### ISSUE TITLE
Google meet 링크 생성 자동화

### ISSUE THREAD

**Issue by ottl-seo** [ottl-seo/ncloud-certification-rpa#3]
## 자동화 순서
초기 1회
1. '로그인' 클릭: `a.glue-header__link`
2. 아이디 입력: `input#identifierId`
3. 비밀번호 입력: `#password > div.aCsJod.oJeWuf > div > div.Xb9hP > input`

반복   

4. '새 회의' 버튼: `div.VfPpkd-xl07Ob-XxIAqe-OWXEXe-oYxtQd > div:nth-child(1) > div > button > div.VfPpkd-RLmnJb`
5. '나중에 진행할 회의 만들기' 버튼: `c-wiz li:nth-child(2) > span.VfPpkd-StrnGf-rymPhb-b9t22c` 
6. copy 아이콘: `div.VKf0Le.u9lF8e div:nth-child(2) > span > button`
7. X 아이콘: `div.u9lF8e div.VfPpkd-oclYLd > button > span > svg`

**Comment by ottl-seo** [comment]
### Selenium 오류: 
AttributeError: 'WebDriver' object has no attribute 'find_element_by_css_selector'  이 오류는 말 그대로 WebDriver에 'find_element_by_css_selector' 라는 함수가 없기 때문에 나타나는 것 이다.

WebDriver에는 find_element라는 함수만 있고 이의 첫번째 매개변수로 By.css_selector 과 같이 뭐를 경로로 사용할지 선택하면 된다. 그리고 두변째 매개변수에 경로를 넣으면 오류 없이 사용 할 수 있다.

이때, 반드시 By를 import 해줘야 한다. 안해주면 NameError: name 'By' is not defined 이런 오류가 뜰 것이다.

```python
login_btn = driver.find_element(By.CSS_SELECTOR, "a.glue-header__link")
login_btn.click()
time.sleep(2)
```

**Comment by ottlseo** [comment]
## 링크 생성 후 값 복사 완료!!
![image](https://user-images.githubusercontent.com/61778930/201486571-6397e724-e3ad-458a-af23-7967ebf79a6b.png)

이제 엑셀에 붙여넣고 반복작업만 하면 된닷 #14
